{{- $ := . -}}
{{- range $.Values.configmap }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: |-
      {{- nindent 8 $value }}
  {{- end }}
immutable: {{ .immutable | default false }}    
{{- end }}
