apiVersion: v1
kind: Service
metadata:
  name: soketi
spec:
  selector:
    app: soketi
    ws.soketi.app/accepts-new-connections: "yes" # required
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
      name: ws