automountServiceAccountToken: true
deployment:
  deploymentList:
    - name: teletype-server
      image: teletype/teletype-server
      tag: latest
      ports:
        - port: 4279
      envConfigList:
        - type: configmap
          name: teletype-server-config
        - type: secret
          name: teletype-server-secret
      service:
        type: ClusterIP
    - name: teletype-data
      image: postgres
      tag: 15.6-bullseye
      ports:
        - port: 5432
      envList:
        POSTGRES_DB: teletype-server
        POSTGRES_USER: teletype-server
      envConfigList:
        - type: secret
          name: teletype-data-secret
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          tmpMountPath: /postgresql_data
          name: teletype-data-claim
      service:
        type: ClusterIP
    - name: soketi
      image: quay.io/soketi/soketi
      tag: 1.6.1-16-alpine
      ports:
        - port: 6001
          name: ws
      envList:
        PORT: 6001
      volumeMounts:
        - name: soketi-config
          type: configmap
          mountPath: /app/config.json
          subPath: config.json
      service:
        type: ClusterIP
        selector:
          - ws.soketi.app/accepts-new-connections: "yes" # required
    - name: coturn
      image: coturn/coturn
      tag: latest
      ports:
        - port: 3478
          protocol: UDP
          name: turn-port1
        - port: 3478
          name: turn-port2
        - port: 5349
          name: turn-port3
        - port: 5349
          name: turn-port4
          protocol: UDP
      args: ["-n", "--min-port=49160", "--max-port=49200", "--log-file=stdout"]
      hostNetwork: true
      service:
        type: ClusterIP
persistence:
  - name: teletype-data-claim
    accessMode: ReadWriteOnce
    existingVolumeClaim: teletype-data-claim
    volumeSize: 1Gi
configmap:
  - name: soketi-config
    data:
      config.json: |-
            {
                "appManager": {
                    "driver": "array",
                    "array": {
                        "apps": [
                            {
                            "id": "1355308",
                            "key": "cc8fb96b89e84d763d6b",
                            "secret": "1882b79e0d1e521226d7",
                            "cluster": "ap3"
                            }
                        ]
                    },
                    "cache": {
                        "enabled": false
                    }
                },
                "port": 6001,
                "debug": true
            }
  - name: teletype-server-config
    data:
      PUSHER_HOST: soketi
      ICE_SERVER: |-
          {
            "username": "teletype",
            "ice_servers": [
              {
                "url": "stun:coturn:3478?transport=udp",
                "urls": "stun:coturn:3478?transport=udp"
              },
              {
                "url": "turn:coturn:3478?transport=udp",
                "urls": "turn:coturn:3478?transport=udp",
                "username": "teletype",
                "credential": "teletype1!"
              },
              {
                "url": "turn:coturn:3478?transport=tcp",
                "urls": "turn:coturn:3478?transport=tcp",
                "username": "teletype",
                "credential": "teletype1!"
              },
              {
                "url": "turn:coturn:443?transport=tcp",
                "urls": "turn:coturn:443?transport=tcp",
                "username": "teletype",
                "credential": "teletype1!"
              }
            ],
            "password": "teletype1!"
          }
secret:
  - name: teletype-server-secret
    data:
      DATABASE_URL: "postgres://teletype-server:teletype1!@teletype-data:5432/teletype-server"
  - name: teletype-data-secret
    data:
      POSTGRES_PASSWORD: 'teletype1!'
replicaCount: 1
resources:
  limits:
    cpu: 1
    memory: 6Gi
  requests:
    cpu: 0.2
    memory: 256Mi
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
terminationGracePeriodSeconds: 30
