automountServiceAccountToken: true
deployment:
  deploymentList:
    - name: teletype-server
      image: dcpdev-rmlorxco.scr.skr-west.scp-in.com/ide/teletype-server
      #tag: latest
      tag: emb_db-latest
      ports:
        - port: 4279
      envConfigList:
        - type: configmap
          name: teletype-server-config
        # - type: secret
        #   name: teletype-server-secret
      service:
        type: ClusterIP
    # - name: teletype-data
    #   image: dcpdev-rmlorxco.scr.skr-west.scp-in.com/ide/postgres
    #   tag: 15.6-bullseye
    #   ports:
    #     - port: 5432
    #   envList:
    #     POSTGRES_DB: teletype
    #     POSTGRES_USER: teletype
    #   envConfigList:
    #     - type: secret
    #       name: teletype-data-secret
    #   volumeMounts:
    #     - mountPath: /var/lib/postgresql/data
    #       tmpMountPath: /postgresql_data
    #       name: teletype-data-claim
    #   service:
    #     type: ClusterIP
    - name: soketi
      image: dcpdev-rmlorxco.scr.skr-west.scp-in.com/ide/soketi
      tag: 1.2.0-16-alpine
      ports:
        - port: 6001
          name: ws
      envList:
        SOKETI_PORT: 6001
        SOKETI_DEBUG: 1
      envConfigList:
        - type: configmap
          name: soketi-config
      service:
        type: ClusterIP
      additionalLabels:
        ws.soketi.app/accepts-new-connections: "yes" # required
    - name: coturn
      image: dcpdev-rmlorxco.scr.skr-west.scp-in.com/ide/coturn
      tag: latest
      ports:
        - port: 3478
          protocol: UDP
          name: turn-port1
        - port: 3478
          name: turn-port2
        - port: 5349
          name: turn-port3
        - port: 5349
          name: turn-port4
          protocol: UDP
      volumeMounts:
        - name: coturn-config
          type: configmap
          mountPath: "/startservice.sh"
          subPath: startservice.sh
      # args: ["-n", "--min-port=49160", "--max-port=49200", "--log-file=stdout"]
      args: ["sh", "/startservice.sh"]
      hostNetwork: true
      service:
        type: ClusterIP
# persistence:
#   - name: teletype-data-claim
#     accessMode: ReadWriteOnce
#     existingVolumeClaim: teletype-data-claim
#     volumeSize: 1Gi
configmap:
  - name: soketi-config
    data:
      SOKETI_DEFAULT_APP_ID: '1355308'
      SOKETI_DEFAULT_APP_KEY: cc8fb96b89e84d763d6b
      SOKETI_DEFAULT_APP_SECRET: 1882b79e0d1e521226d7
  - name: teletype-server-config
    data:
      PUSHER_HOST: soketi
      ICE_SERVER: |-
          {
            "ice_servers": [
              {
                "url": "stun:coturn:3478?transport=udp",
                "urls": "stun:coturn:3478?transport=udp"
              },
              {
                "url": "turn:coturn:3478?transport=udp",
                "urls": "turn:coturn:3478?transport=udp",
                "username": "teletype",
                "credential": "teletype1!"
              },
              {
                "url": "turn:coturn:3478?transport=tcp",
                "urls": "turn:coturn:3478?transport=tcp",
                "username": "teletype",
                "credential": "teletype1!"
              },
              {
                "url": "turn:coturn:443?transport=tcp",
                "urls": "turn:coturn:443?transport=tcp",
                "username": "teletype",
                "credential": "teletype1!"
              }
            ],
            "username": "teletype",
            "password": "teletype1!"
          }
  - name: coturn-config
    data:
      startservice.sh: |
          turnadmin -O -r teletype -o teletype
          turnadmin -a -u teletype -p teletype1! -r teletype
          turnserver -n --min-port=49160 --max-port=49200 --log-file=stdout
# secret:
  # - name: teletype-server-secret
  #   data:
  #     DATABASE_URL: "postgres://teletype:teletype1!@teletype-data:5432/teletype"
  # - name: teletype-data-secret
  #   data:
  #     POSTGRES_PASSWORD: 'teletype1!'
  # - name: soketi-config-secret
  #   data:
  #     SOKETI_DEFAULT_APP_SECRET: '1882b79e0d1e521226d7'
replicaCount: 1
resources:
  limits:
    cpu: 1
    memory: 6Gi
  requests:
    cpu: 0.2
    memory: 256Mi
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
terminationGracePeriodSeconds: 30
