apiVersion: apps/v1
kind: Deployment
metadata:
  name: teletype-server
  labels:
    app.kubernetes.io/name: teletype-server
    app.kubernetes.io/instance: teletype-server
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:           
      app.kubernetes.io/name: teletype-server
      app.kubernetes.io/instance: teletype-server
      app.kubernetes.io/version: 0.0.1    
  replicas: 1
  template:
    metadata:
      labels:         
        app.kubernetes.io/name: teletype-server
        app.kubernetes.io/instance: teletype-server
        app.kubernetes.io/version: 0.0.1       
    spec:
      containers:
      - name: teletype-server
        image: teletype/teletype-server:emb_db-latest
        ports:
        - containerPort: 4279
        envFrom:
          - configMapRef:
              name: teletype-server-config