apiVersion: v1
kind: Service
metadata:
  name: teletype-server
  labels:
    app.kubernetes.io/name: teletype-server
    app.kubernetes.io/instance: teletype-server
    app.kubernetes.io/version: 0.0.1
spec:
  type: ClusterIP
  ports:
    - port: 4279
      targetPort: 4279
      name: teletype-server
      protocol: TCP
  selector:
    app.kubernetes.io/name: teletype-server
    app.kubernetes.io/instance: teletype-server
    app.kubernetes.io/version: 0.0.1
