apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/instance: coturn
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
          app.kubernetes.io/name: coturn
          app.kubernetes.io/instance: coturn
          app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
            app.kubernetes.io/name: coturn
            app.kubernetes.io/instance: coturn
            app.kubernetes.io/version: 0.0.1
    spec:
      hostNetwork: true
      containers:
        - name: coturn
          image: coturn/coturn
          imagePullPolicy: Always
          ports:
            - name: turn-port1
              containerPort: 3478
              hostPort: 3478
              protocol: UDP
            - name: turn-port2
              containerPort: 3478
              hostPort: 3478
              protocol: TCP
            - name: turn-port3
              containerPort: 5349
              hostPort: 5349
              protocol: TCP
            - name: turn-port4
              containerPort: 5349
              hostPort: 5349
              protocol: UDP
          volumeMounts:
            - name: coturn-config
              mountPath: /startservice.sh
              subPath: startservice.sh              
          args: ["sh", "/startservice.sh"]
      volumes:
        - name: coturn-config
          configMap:
            name: coturn-config
            defaultMode: 420
