apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels:
       app.kubernetes.io/name: coturn
       app.kubernetes.io/instance: coturn
       app.kubernetes.io/version: 0.0.1
spec:
  type: ClusterIP
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-port1
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: turn-port2
    - name: turn-port3
      port: 5349
      targetPort: 5349
      protocol: TCP
    - name: turn-port4
      port: 5349
      targetPort: 5349
      protocol: UDP
  selector:
       app.kubernetes.io/name: coturn
       app.kubernetes.io/instance: coturn
       app.kubernetes.io/version: 0.0.1
